base_config: &BASE_CONFIG
    #data
    exp_dir: '/lustre/Linlin.Cui/mlsfs/results'
    train_data_path: '/lustre/Linlin.Cui/mlsfs/data/UFS/train' 
    valid_data_path: '/lustre/Linlin.Cui/mlsfs/data/UFS/test' 
    global_means_path: '/lustre/Linlin.Cui/mlsfs/data/UFS/stats/global_mean_ufs_1994-2016_chn85.npy'
    global_stds_path:  '/lustre/Linlin.Cui/mlsfs/data/UFS/stats/global_std_ufs_1994-2016_chn85.npy'

    #architecture related
    nettype: "sfno"
    sht_grid_type: "legendre-gauss"
    filter_type: "linear"
    model_grid: "legendre-gauss"
    scale_factor: 3
    embed_dim: 192
    num_layers: 8
    normalization_lyaer: "instance_norm"
    hard_thresholding_fraction: 0.9
    use_mpl: !!bool True
    mlp_mode: "serial"
    mlp_ratio: 2
    operator_type: "dhconv"
    activation_function: "gelu"
    pos_embed: "none" # "none", "direct" or "frequency". For resoltuion invariance, use add_grid instead or use "frequency"

    # training parameters
    loss: 'l2'
    lr: 1E-4
    max_epochs: 300
    batch_size: 64

    #scheduler parameters
    scheduler: 'CosineAnnealingLR' #"StepLR", #ReduceLROnPlateau"
    scheduler_T_max: 75
    scheduler_min_lr: 1E-6
    scheduler_factor: 0.1
    scheduler_patience: 10
    scheduler_step_size: 100
    scheduler_gamma: 0.5
    lr_warmup_steps: 0


    num_data_workers: 8
    dt: 1 # how many timesteps ahead the model will predict
    n_history: 0 #how many previous timesteps to consider

    normalization: 'zscore' #options zscore (minmax not supported) 
    normalize: !!bool True

    orography: !!bool True
    orography_file: /lustre/Linlin.Cui/mlsfs/data/UFS/static/orog_latlon_ns_normalized.npy
    lsmask: !!bool True
    lsm_file: /lustre/Linlin.Cui/mlsfs/data/UFS/static/land_latlon_ns_normalized.npy
    lakemask: !!bool False
    lake_file: None

    log_to_screen: !!bool True
    log_to_wandb: !!bool False
    save_checkpoint: !!bool True

    enable_nhwc: !!bool False
    crop_size_x: None
    crop_size_y: None

    optimizer_type: 'Adam'
    optimizer_beta1: 0.9
    optimizer_beta2: 0.95
    optimizer_max_grad_norm: 32

    multi_step_training: !!bool False
    nfutures: 0

sfno_backbone: &backbone
    <<: *BASE_CONFIG
    n_out_channels: 83 #u10, v10, t2m, prmsl, tcwv, [u, v, w, t, q, z] at 13
    n_forcing_channels: 2 #time-dependent forcing (tisr + sst)
    vars_surface: ['10m_u_component_of_wind', '10m_v_component_of_wind', '2m_temperature', 'mean_sea_level_pressure', 'precipitable_water']
    vars_pl: ['u_component_of_wind', 'v_component_of_wind', 'vertical_velocity', 'temperature', 'specific_humidity', 'geopotential']
    vars_forcing: ['toa_incident_solar_radiation', 'sea_surface_temperature']
    levels: [1000, 925, 850, 700, 600, 500, 400, 300, 250, 200, 150, 100, 50]
